### ISSUE TITLE
Failure to sync, 401 Client Error: Unauthorized for url: https://client.fitbit.com:443/tracker/client/message

### ISSUE THREAD

**Issue by Drathus** [benallard/galileo#8]
I hope this is the correct place to report issues, the referenced bitbucket link is no longer valid.  

--

```
galileo -vvv --force
2023-04-11 11:52:17,532:INFO: Disconnecting from any connected trackers
2023-04-11 11:52:19,542:INFO: Got an I/O Timeout (> 2000ms) while reading!
2023-04-11 11:52:19,546:INFO: Discovering trackers to synchronize
2023-04-11 11:52:19,550:INFO: Ignoring message: StartDiscovery
2023-04-11 11:52:23,554:INFO: 1 trackers discovered
2023-04-11 11:52:23,554:INFO: Tracker F1E391B365D7 was recently synchronized, but forcing synchronization anyway
2023-04-11 11:52:23,554:INFO: Attempting to synchronize tracker F1E391B365D7
2023-04-11 11:52:24,015:CRITICAL: # A serious error happened, which is probably due to a
2023-04-11 11:52:24,015:CRITICAL: # programming error. Please open a new issue with the following
2023-04-11 11:52:24,015:CRITICAL: # information on the galileo bug tracker:
2023-04-11 11:52:24,015:CRITICAL: #    https://bitbucket.org/benallard/galileo/issues/new
2023-04-11 11:52:24,017:CRITICAL: # /usr/local/bin/galileo: 0.5.1
# Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
# Platform: Linux nyx 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64
# pyusb: 1.2.1-1
# requests: 2.25.1
# yaml: 5.4.1 (with libyaml)
2023-04-11 11:52:24,017:CRITICAL: # Last communications:
2023-04-11 11:52:24,017:CRITICAL: # < 20 01 54 65 72 6D 69 6E 61 74 65 4C 69 6E 6B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 11:52:24,017:CRITICAL: # < 
2023-04-11 11:52:24,017:CRITICAL: # > 02 01
2023-04-11 11:52:24,018:CRITICAL: # < 15 08 01 06 E4 76 CE F3 7B 98 74 04 00 20 00 00 FF E7 01 00 02 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 11:52:24,018:CRITICAL: # > 1A 04 BA 56 89 A6 FA BF A2 BD 01 46 7D 6E 00 00 AB AD 00 FB 01 FB 02 FB A0 0F
2023-04-11 11:52:24,018:CRITICAL: # < 20 01 53 74 61 72 74 44 69 73 63 6F 76 65 72 79 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 11:52:24,018:CRITICAL: # < 13 03 F1 E3 91 B3 65 D7 01 C4 02 02 06 03 32 31 80 87 05 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 11:52:24,018:CRITICAL: # < 03 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 11:52:24,018:CRITICAL: # > 02 05
2023-04-11 11:52:24,018:CRITICAL: # < 20 01 43 61 6E 63 65 6C 44 69 73 63 6F 76 65 72 79 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 11:52:24,018:CRITICAL: #
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/galileo/main.py", line 280, in main
    {
  File "/usr/local/lib/python3.10/dist-packages/galileo/main.py", line 193, in sync
    for tracker in syncAllTrackers(config):
  File "/usr/local/lib/python3.10/dist-packages/galileo/main.py", line 71, in syncAllTrackers
    if not galileo.requestStatus(not config.httpsOnly):
  File "/usr/local/lib/python3.10/dist-packages/galileo/net.py", line 187, in requestStatus
    self.post('status')
  File "/usr/local/lib/python3.10/dist-packages/galileo/net.py", line 134, in post
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://client.fitbit.com:443/tracker/client/message
```

**Comment by benallard** [comment]
Yes, thanks, that's the right place.

Does the error remains? Could be a temporary issue on their side.

**Comment by Drathus** [comment]
It hasn't synced through galileo at least a few weeks. I was able to sync it today via the fitbit app on my phone, hence why I had to --force it when re-testing after that. So it seems to be able to query about the tracker, but not post an update.

From earlier:

```
galileo -vvv
2023-04-11 11:51:29,397:INFO: Disconnecting from any connected trackers
2023-04-11 11:51:31,406:INFO: Got an I/O Timeout (> 2000ms) while reading!
2023-04-11 11:51:31,410:INFO: Discovering trackers to synchronize
2023-04-11 11:51:31,414:INFO: Ignoring message: StartDiscovery
2023-04-11 11:51:35,418:INFO: 1 trackers discovered
2023-04-11 11:51:35,418:INFO: Tracker F1E391B365D7 was recently synchronized; skipping for now
2023-04-11 11:51:35,418:INFO: Tracker F1E391B365D7 skipped due to configuration
Tracker: F1E391B365D7: Skipped because recently synchronised
```

And again just now:
```
galileo -vvv
2023-04-11 14:59:10,589:INFO: Disconnecting from any connected trackers
2023-04-11 14:59:12,600:INFO: Got an I/O Timeout (> 2000ms) while reading!
2023-04-11 14:59:12,603:INFO: Discovering trackers to synchronize
2023-04-11 14:59:12,607:INFO: Ignoring message: StartDiscovery
2023-04-11 14:59:16,611:INFO: 1 trackers discovered
2023-04-11 14:59:16,612:INFO: Attempting to synchronize tracker F1E391B365D7
2023-04-11 14:59:16,809:CRITICAL: # A serious error happened, which is probably due to a
2023-04-11 14:59:16,809:CRITICAL: # programming error. Please open a new issue with the following
2023-04-11 14:59:16,809:CRITICAL: # information on the galileo bug tracker:
2023-04-11 14:59:16,809:CRITICAL: #    https://bitbucket.org/benallard/galileo/issues/new
2023-04-11 14:59:16,811:CRITICAL: # /usr/local/bin/galileo: 0.5.1
# Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
# Platform: Linux nyx 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64
# pyusb: 1.2.1-1
# requests: 2.25.1
# yaml: 5.4.1 (with libyaml)
2023-04-11 14:59:16,811:CRITICAL: # Last communications:
2023-04-11 14:59:16,811:CRITICAL: # < 20 01 54 65 72 6D 69 6E 61 74 65 4C 69 6E 6B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 14:59:16,811:CRITICAL: # < 
2023-04-11 14:59:16,811:CRITICAL: # > 02 01
2023-04-11 14:59:16,811:CRITICAL: # < 15 08 01 06 E4 76 CE F3 7B 98 74 04 00 20 00 00 FF E7 01 00 02 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 14:59:16,811:CRITICAL: # > 1A 04 BA 56 89 A6 FA BF A2 BD 01 46 7D 6E 00 00 AB AD 00 FB 01 FB 02 FB A0 0F
2023-04-11 14:59:16,811:CRITICAL: # < 20 01 53 74 61 72 74 44 69 73 63 6F 76 65 72 79 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 14:59:16,811:CRITICAL: # < 13 03 F1 E3 91 B3 65 D7 01 C3 02 02 04 03 32 31 4B 87 05 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 14:59:16,811:CRITICAL: # < 03 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 14:59:16,811:CRITICAL: # > 02 05
2023-04-11 14:59:16,811:CRITICAL: # < 20 01 43 61 6E 63 65 6C 44 69 73 63 6F 76 65 72 79 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-11 14:59:16,812:CRITICAL: #
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/galileo/main.py", line 280, in main
    {
  File "/usr/local/lib/python3.10/dist-packages/galileo/main.py", line 193, in sync
    for tracker in syncAllTrackers(config):
  File "/usr/local/lib/python3.10/dist-packages/galileo/main.py", line 71, in syncAllTrackers
    if not galileo.requestStatus(not config.httpsOnly):
  File "/usr/local/lib/python3.10/dist-packages/galileo/net.py", line 187, in requestStatus
    self.post('status')
  File "/usr/local/lib/python3.10/dist-packages/galileo/net.py", line 134, in post
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://client.fitbit.com:443/tracker/client/message
```
Not sure if it started after an upgrade of some form, but I've reinstalled my os (Mint) recently (3/12) and it hasn't worked successfully at least since then.

**Comment by benallard** [comment]
Nah, that‘s not a mistake on your side. The server is claiming that no synchronisation can be made without prior login. Looks like they changed that part as well.

**Comment by Drathus** [comment]
Yeah, I want to say that I saw it wasn't syncing correctly prior to putting in a new SSD on my system (hence the OS redo) but I couldn't remember for sure; the timing was at least *very* coincidental. :)

**Comment by ajp233** [comment]
2023-04-21 10:57:07,618:INFO: Disconnecting from any connected trackers
2023-04-21 10:57:09,623:INFO: Got an I/O Timeout (> 2000ms) while reading!
2023-04-21 10:57:09,626:INFO: Discovering trackers to synchronize
2023-04-21 10:57:09,630:INFO: Ignoring message: StartDiscovery
2023-04-21 10:57:13,652:INFO: 1 trackers discovered
2023-04-21 10:57:13,652:INFO: Attempting to synchronize tracker C7010897B8C1
2023-04-21 10:57:14,096:CRITICAL: # A serious error happened, which is probably due to a
2023-04-21 10:57:14,097:CRITICAL: # programming error. Please open a new issue with the following
2023-04-21 10:57:14,097:CRITICAL: # information on the galileo bug tracker:
2023-04-21 10:57:14,097:CRITICAL: #    https://bitbucket.org/benallard/galileo/issues/new
2023-04-21 10:57:14,098:CRITICAL: # /usr/bin/galileo: 0.5.1
#Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
#Platform: Linux MacBookAir 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64
#pyusb: 1.2.1-1
#requests: 2.25.1
#yaml: 5.4.1 (with libyaml)
2023-04-21 10:57:14,098:CRITICAL: # Last communications:
2023-04-21 10:57:14,098:CRITICAL: # < 20 01 54 65 72 6D 69 6E 61 74 65 4C 69 6E 6B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-21 10:57:14,099:CRITICAL: # < 
2023-04-21 10:57:14,099:CRITICAL: # > 02 01
2023-04-21 10:57:14,099:CRITICAL: # < 16 08 02 05 A0 C3 D2 79 EC 7C 74 04 00 20 00 00 FF E7 01 00 02 00 00 00 00 00 00 00 00 00 00 00
2023-04-21 10:57:14,099:CRITICAL: # > 1A 04 BA 56 89 A6 FA BF A2 BD 01 46 7D 6E 00 00 AB AD 00 FB 01 FB 02 FB A0 0F
2023-04-21 10:57:14,099:CRITICAL: # < 20 01 53 74 61 72 74 44 69 73 63 6F 76 65 72 79 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-21 10:57:14,099:CRITICAL: # < 13 03 C7 01 08 97 B8 C1 01 C7 02 02 04 00 81 BF E6 57 77 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-21 10:57:14,099:CRITICAL: # < 03 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-21 10:57:14,099:CRITICAL: # > 02 05
2023-04-21 10:57:14,099:CRITICAL: # < 20 01 43 61 6E 63 65 6C 44 69 73 63 6F 76 65 72 79 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2023-04-21 10:57:14,099:CRITICAL: #
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/galileo/main.py", line 280, in main
    {
  File "/usr/lib/python3/dist-packages/galileo/main.py", line 193, in sync
    for tracker in syncAllTrackers(config):
  File "/usr/lib/python3/dist-packages/galileo/main.py", line 71, in syncAllTrackers
    if not galileo.requestStatus(not config.httpsOnly):
  File "/usr/lib/python3/dist-packages/galileo/net.py", line 187, in requestStatus
    self.post('status')
  File "/usr/lib/python3/dist-packages/galileo/net.py", line 134, in post
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://client.fitbit.com:443/tracker/client/message

**Comment by ajp233** [comment]
https://www.xda-developers.com/fitbit-shutters-fitbit-connect-on-pc-and-mac/

**Comment by benallard** [comment]
Thanks for the link. Well, that confirm my suspicion about the error you posted. You have to login in the app anyway, so there is no problem using that login to sync the data (what’s missing here).

On the one side, it would be interesting to see if we can get that to work(now that galileo seems to be the only remaining sync-tool for desktop platform), but I’m not sure it’s worth the effort.

i believe a big warning on top of the README seems to be required now.

**Comment by ajp233** [comment]
I'm not a programmer so don't know if this will help trying to get galileo working again - https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/

It's been fab being able to use my Fitbit usb dongle to sync via Linux.
